apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | quote }}
data:
  DB_HOST: {{ .Values.configMap.DB_HOST | quote }}
  DB_NAME: {{ .Values.configMap.DB_NAME | quote }}
  DB_PORT: {{ .Values.configMap.DB_PORT | quote }}
  DB_USER: {{ .Values.configMap.DB_USER | quote }}