apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  selector:
    app: {{ .Values.mysql.appLabel }}
  ports:
    - name: {{ .Values.mysql.service.portName }}
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}