apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.todoService.name }}
spec:
  selector:
    app: {{ include "go-todo-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.todoService.port }}
      targetPort: {{ .Values.todoService.targetPort }}
      nodePort: {{ .Values.todoService.nodePort }}
  type: {{ .Values.todoService.type }}